//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZGF.Revit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastExportFolder {
            get {
                return ((string)(this["LastExportFolder"]));
            }
            set {
                this["LastExportFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CheckedCategories {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CheckedCategories"]));
            }
            set {
                this["CheckedCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverwriteExistingFiles {
            get {
                return ((bool)(this["OverwriteExistingFiles"]));
            }
            set {
                this["OverwriteExistingFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DoNotExportAutodeskFamilies {
            get {
                return ((bool)(this["DoNotExportAutodeskFamilies"]));
            }
            set {
                this["DoNotExportAutodeskFamilies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeleteBackupFiles {
            get {
                return ((bool)(this["DeleteBackupFiles"]));
            }
            set {
                this["DeleteBackupFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastImportFolder {
            get {
                return ((string)(this["LastImportFolder"]));
            }
            set {
                this["LastImportFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportRecurseFolders {
            get {
                return ((bool)(this["ImportRecurseFolders"]));
            }
            set {
                this["ImportRecurseFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ImportUpdateTypeProperties {
            get {
                return ((bool)(this["ImportUpdateTypeProperties"]));
            }
            set {
                this["ImportUpdateTypeProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportNewFamiliesOnly {
            get {
                return ((bool)(this["ImportNewFamiliesOnly"]));
            }
            set {
                this["ImportNewFamiliesOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string browserLocalLastSearch {
            get {
                return ((string)(this["browserLocalLastSearch"]));
            }
            set {
                this["browserLocalLastSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection browserLocalSearchHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["browserLocalSearchHistory"]));
            }
            set {
                this["browserLocalSearchHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool browserStartWithLastSearch {
            get {
                return ((bool)(this["browserStartWithLastSearch"]));
            }
            set {
                this["browserStartWithLastSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int browserMaxSearchHistoryItems {
            get {
                return ((int)(this["browserMaxSearchHistoryItems"]));
            }
            set {
                this["browserMaxSearchHistoryItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750, 530")]
        public global::System.Drawing.Size browserLastSize {
            get {
                return ((global::System.Drawing.Size)(this["browserLastSize"]));
            }
            set {
                this["browserLastSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool browserStartWithLocalContent {
            get {
                return ((bool)(this["browserStartWithLocalContent"]));
            }
            set {
                this["browserStartWithLocalContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string browserExternalLastSearch {
            get {
                return ((string)(this["browserExternalLastSearch"]));
            }
            set {
                this["browserExternalLastSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection browserExternalSearchHIstory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["browserExternalSearchHIstory"]));
            }
            set {
                this["browserExternalSearchHIstory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewFinderLastSearch {
            get {
                return ((string)(this["ViewFinderLastSearch"]));
            }
            set {
                this["ViewFinderLastSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewFinderRememberSearch {
            get {
                return ((bool)(this["ViewFinderRememberSearch"]));
            }
            set {
                this["ViewFinderRememberSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size ViewFinderSize {
            get {
                return ((global::System.Drawing.Size)(this["ViewFinderSize"]));
            }
            set {
                this["ViewFinderSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewFinderColDiscipline {
            get {
                return ((bool)(this["ViewFinderColDiscipline"]));
            }
            set {
                this["ViewFinderColDiscipline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewFinderColPhase {
            get {
                return ((bool)(this["ViewFinderColPhase"]));
            }
            set {
                this["ViewFinderColPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewFinderColRefSheet {
            get {
                return ((bool)(this["ViewFinderColRefSheet"]));
            }
            set {
                this["ViewFinderColRefSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewFinderColScale {
            get {
                return ((bool)(this["ViewFinderColScale"]));
            }
            set {
                this["ViewFinderColScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewFinderColTitleOnSheet {
            get {
                return ((bool)(this["ViewFinderColTitleOnSheet"]));
            }
            set {
                this["ViewFinderColTitleOnSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int colViewCWidDiscipline {
            get {
                return ((int)(this["colViewCWidDiscipline"]));
            }
            set {
                this["colViewCWidDiscipline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int colViewCWidPhase {
            get {
                return ((int)(this["colViewCWidPhase"]));
            }
            set {
                this["colViewCWidPhase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int colViewCWidRefSht {
            get {
                return ((int)(this["colViewCWidRefSht"]));
            }
            set {
                this["colViewCWidRefSht"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int colViewCWidScale {
            get {
                return ((int)(this["colViewCWidScale"]));
            }
            set {
                this["colViewCWidScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int colViewCWidTitleOnSheet {
            get {
                return ((int)(this["colViewCWidTitleOnSheet"]));
            }
            set {
                this["colViewCWidTitleOnSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int colViewCWidName {
            get {
                return ((int)(this["colViewCWidName"]));
            }
            set {
                this["colViewCWidName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ViewFinderSortedColumnIndex {
            get {
                return ((int)(this["ViewFinderSortedColumnIndex"]));
            }
            set {
                this["ViewFinderSortedColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ascending")]
        public global::System.ComponentModel.ListSortDirection ViewFinderSortedColumnSortDirection {
            get {
                return ((global::System.ComponentModel.ListSortDirection)(this["ViewFinderSortedColumnSortDirection"]));
            }
            set {
                this["ViewFinderSortedColumnSortDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewFinderColViewTypeName {
            get {
                return ((bool)(this["ViewFinderColViewTypeName"]));
            }
            set {
                this["ViewFinderColViewTypeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewFinderPreviewToggle {
            get {
                return ((bool)(this["ViewFinderPreviewToggle"]));
            }
            set {
                this["ViewFinderPreviewToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ViewFinderSearchHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ViewFinderSearchHistory"]));
            }
            set {
                this["ViewFinderSearchHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ViewFinderCloseAfterActivate {
            get {
                return ((bool)(this["ViewFinderCloseAfterActivate"]));
            }
            set {
                this["ViewFinderCloseAfterActivate"] = value;
            }
        }
    }
}
